import Head from "next/head";
import { ThemeProvider } from "next-themes";
import NavBar from "@/components/NavBar";
import QuizList from "@/components/QuizList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quizit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
        <NavBar />
        <div className="container flex flex-wrap bg-background pt-10">
          <QuizList />
        </div>
      </ThemeProvider>
    </>
  );
}
