import Head from "next/head";
import QuizList from "@/components/QuizList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quizit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QuizList name={null} />
    </>
  );
}
